#!/usr/bin/with-contenv bash

variables='${PHP_MEMORY_LIMIT}:${PHP_ERROR_REPORTING}:${TZ}'
envsubst "${variables}" < php-cli.ini.tmpl > /etc/php/7.3/cli/php.ini
envsubst "${variables}" < php-fpm.ini.tmpl > /etc/php/7.3/fpm/php.ini

exec php-fpm7.3
